Enhancement/create receipt template/4
gri-is/selfcheck pull request #22
Opened 2017-02-14 23:37 UTC by dnoneill

closes #4 

footer logo loads after print.  small bug, not sure if worth fixing.

2017-02-23 20:12 UTC, joshuago78 requested changes
- Bugs should not be in the README
- put back the requirements file

2017-02-23 20:12 UTC, joshuago78 commented on README.md
> +Bugs:
Bugs and requirements do not belong in the README

2017-02-23 20:12 UTC, joshuago78 commented on requirements.txt
> -Flask
These requirements should not have been deleted

2017-02-23 20:12 UTC, joshuago78 commented on static/js/mustache.js
> + * mustache.js - Logic-less {{mustache}} templates with JavaScript
You should link to this js library instead of including it in the source code. See here: https://cdnjs.com/libraries/mustache.js/

2017-02-23 20:12 UTC, joshuago78 commented on static/js/self-check.js
> +    		$.getScript("static/js/mustache.js", function(){
again, you don't need to do this if you just include the mustache code in a <script> tag at the top of the file.

2017-02-23 20:12 UTC, joshuago78 commented on static/receipt.mustache
> +<html>
you should give this a .html file extension

2017-02-23 20:12 UTC, joshuago78 commented on static/self-check.html
> +		<script type="text/javascript"></script>
empty script tag

2017-02-23 22:29 UTC, dnoneill commented
@joshuago78 Applied requested changes.

2017-02-24 18:15 UTC, joshuago78 approved these changes

2017-02-24 18:16 UTC, merged